spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE #MVCC 설정해주면 여러개 한번에 접근시 더빨리 처리, 권장이니까 그냥 넣어주기
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # System.out으로 출력
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug # 로거를 통해서 출력
